import { VMSConfig, AdvanceFiltter } from '../../../library/smartTable/table/table.model';

export const advanceFilter: AdvanceFiltter[] = [
  {
    name: 'report_name',
    title: 'Report Name',
    filterType: 'TEXT',
  },
  {
    name: 'report_creator',
    title: 'Search By Report Creator',
    filterType: 'TEXT',
  },
  {
    name: 'created_on',
    title: 'Created On',
    filterType: 'DATERANGE',
  },
  {
    name: 'last_run_on',
    title: 'Last Run On',
    filterType: 'DATERANGE',
  },
  {
    name: 'status',
    title: 'Schedule Status',
    filterType: 'SELECT',
    multiSelectData: [
      {
        name: 'Scheduled',
        value: true,
      },
      {
        name: 'Not Scheduled',
        value: false,
      },
    ],
  },
];

export const ReportsSavedTableModel: VMSConfig = {
  title: 'All Saved Reports',
  columnList: [
    {
      name: 'report_name',
      title: 'Report Name',
      width: 20,
      isIcon: false,
      isImage: true,
      isContact: false,
      isNumberBadge: false,
      isSort: true,
      isClickable: true,
      showTitleCase: true,
      toolTipVisibility: true,
      options: [
        { name: 'View Filters & Fields' },
        { name: 'Edit Filters & Fields' },
        { name: 'New Schedule' },
        { name: 'View Schedules' },
        { name: 'Share' },
      ],
    }, //{name: 'Schedule Report'},
    {
      name: 'base_report',
      title: 'Base Report',
      width: 15,
      isIcon: false,
      isImage: true,
      isContact: false,
      isNumberBadge: false,
      isNoOption: true,
      isClickable: true,
    },
    {
      name: 'report_creator',
      title: 'Report Creator',
      width: 15,
      isIcon: true,
      isImage: false,
      isContact: false,
      isNumberBadge: false,
      isNoOption: true,
    },
    { name: 'created_on', title: 'Created On', width: 10, isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
    { name: 'last_updated_on', title: 'Last Updated On', width: 10, isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
    { name: 'last_run_on', title: 'Last Run On', width: 10, isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
    { name: 'schedule_status', title: 'Schedule Status', width: 10, isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
    { name: 'is_report', title: 'Status', width: 10, isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
  ],
  isExpand: false,
  isFilter: false, // Set to false as part of V2M-11872
  isSearch: true,
  isSetting: true,
  isSort: true,
  isTopPagination: true,
  isCreate: false,
  density: 'COMFORTABLE',
  tableWidth: '1500px',
  advanceFilter,
};

export const ReportsSavedItemTableModel: VMSConfig = {
  title: 'All Saved Reports',
  subTitle: '',
  columnList: [
    {
      name: 'report_name',
      title: 'Report Name',
      width: 20,
      isIcon: false,
      isImage: true,
      isContact: false,
      isNumberBadge: false,
      isSort: true,
      isClickable: true,
      showTitleCase: true,
      toolTipVisibility: true,
      options: [
        { name: 'View Filters & Fields' },
        { name: 'Edit Filters & Fields' },
        { name: 'Schedule Report' },
        { name: 'New Schedule' },
        { name: 'View Schedules' },
        { name: 'Share' },
      ],
    },
    {
      name: 'base_report',
      title: 'Base Report',
      width: 15,
      isIcon: false,
      isImage: true,
      isContact: false,
      isNumberBadge: false,
      isNoOption: true,
      isClickable: true,
    },
    {
      name: 'report_creator',
      title: 'Report Creator',
      width: 15,
      isIcon: true,
      isImage: false,
      isContact: false,
      isNumberBadge: false,
      isNoOption: true,
    },
    { name: 'created_on', title: 'Created On', width: 10, isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
    { name: 'last_updated_on', title: 'Last Updated On', width: 10, isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
    { name: 'last_run_on', title: 'Last Run On', width: 10, isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
    { name: 'schedule_status', title: 'Schedule Status', width: 10, isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
    { name: 'is_report', title: 'Status', width: 10, isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
  ],
  isExpand: false,
  isFilter: false, // Set to false as part of V2M-11872
  isSearch: true,
  isSetting: true,
  isSort: true,
  isTopPagination: true,
  isViewBaseReport: true,
  isCreate: false,
  density: 'COMFORTABLE',
  tableWidth: '1500px',
  advanceFilter,
};
