import { ExpenseColumns } from '../../enums/expense-detail.enum';
import { VMSConfig } from '../../../library/simple-table/simple-table/simple-table.model';

export const ExpenseDetailTableModel: VMSConfig = {
  title: 'Expenses',
  columnList: [
    {
      name: ExpenseColumns.ExpenseType,
      title: 'Expense Type',
      isIcon: true,
      isImage: true,
      isContact: false,
      isNumberBadge: false,
      isNoOption: true,
      isVieworEdit: true,
      isDelete: true,
      isCurrency: false,
    },
    {
      name: ExpenseColumns.DateIncurred,
      title: 'Date Incurred',
      isIcon: false,
      isImage: false,
      isContact: false,
      isNumberBadge: false,
      isFIle: false,
      isDescription: true,
      isCurrency: false,
    },
    {
      name: ExpenseColumns.Attachment,
      title: 'Attachment',
      isIcon: false,
      isImage: false,
      isContact: false,
      isNumberBadge: false,
      isFIle: true,
      isCurrency: false,
    },
    {
      name: ExpenseColumns.Notes,
      title: 'Notes',
      isIcon: false,
      isImage: false,
      isContact: false,
      isNumberBadge: false,
      isFIle: false,
      isDescription: true,
      isCurrency: false,
    },
     {
      name:ExpenseColumns.TotalAmountWithoutTax,
      title:'Total Amount Without Tax',
      isCurrency: true,
    },
    {
      name: ExpenseColumns.TotalClientTaxAmount,
      title: 'Tax Amount',
      isCurrency: true,
    },
    {
      name: ExpenseColumns.TotalMspAmount,
      title: 'Total MSP Amount',
      isCurrency: true,
    },
    {
      name: ExpenseColumns.VendorAmount,
      title: 'Vendor Amount',
      isCurrency: true,
    },
    {
      name: ExpenseColumns.TotalVendorAmount,
      title: 'Total Vendor Billable Amount',
      isCurrency: true,
    },
    {
      name: ExpenseColumns.TotalClientBillableAmount,
      title: 'Total Client Billable Amount',
      isCurrency: true,
    },
    {
      name:ExpenseColumns.TotalAmount,
      title:'Total Amount',
      isCurrency: true,
    },
  ],
  isExpand: false,
  isFilter: false,
  isSearch: false,
  isSetting: false,
  isTopPagination: false,
  isCreate: false,
  isCreateButtonName: 'Add New Expense Item',
  density: 'COMFORTABLE',
  permission: 'view_expense',
  hasLongText: true,
};

export const RevisionHistoryTableModel: VMSConfig = {
  title: 'Expense Revision History',
  columnList: [
    { name: 'expense_code', title: 'Expense ID', isIcon: false, isImage: true, isContact: false, isNumberBadge: false, isNoOption: true },
    { name: 'expense_status', title: 'Status', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
    { name: 'submitted_date', title: 'Submitted Date', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
    { name: 'items', title: 'Items', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
    {
      name: 'total_billable_amount',
      title: 'Total Billable Amount',
      isIcon: false,
      isImage: false,
      isContact: false,
      isNumberBadge: false,
      isCurrency: true,
    },
    { name: 'assignment_title', title: 'Assignment Name (ID)', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
  ],
  isExpand: false,
  isFilter: false,
  showTabs: false,
  isSearch: false,
  isSort: false,
  isSetting: false,
  isTopPagination: false,
  isCreate: false,
  density: 'COMFORTABLE',
  permission: 'view_expense',
};
