pipelines:
  branches:
    default:
      - step:
          name: Build and test
          caches:
            - node
          script:
            - npm install
            - npm run build 
          artifacts:
            - dist/**