let sideBarOptions: Array<any> = [
  {
    name: 'program',
    icon: 'layers',
    submenuItem: [
      {
        icon: 'info',
        name: 'program_details',
        path: '/program/program-details',
        permission: 'program_details_view',
        menuActive: ['/program/program-details'],
      },
      {
        icon: 'account_tree',
        name: 'hierarchies',
        path: '/program/hierarchy/list',
        permission: 'hierarchy_view',
        menuActive: ['/program/hierarchy/list', 'program/hierarchy/create', '/program/hierarchy/view', '/program/hierarchy/edit'],
      },
      {
        icon: 'area_chart',
        name: 'master_data_types',
        path: '/program/master-data-type/list',
        permission: 'master_data_view',
        menuActive: ['/program/master-data-type/list', 'program/master-data-type/create', '/program/master-data-type/view'],
      },
      {
        icon: 'pin_drop',
        name: 'work_locations',
        path: '/program/work-location/list',
        permission: 'work_location_view',
        menuActive: [
          '/program/work-location/list',
          '/program/work-location/create',
          '/program/work-location/view',
          '/program/work-location/edit',
        ],
      },
      {
        icon: 'device_hub',
        name: 'hiring_process',
        path: '/program/program-setup/hiring-process',
        permission: 'hiring_process_manage',
        menuActive: ['/program/program-setup/hiring-process'],
      },
      {
        icon: 'task_alt',
        name: 'workflows',
        path: '/program/workflow/list',
        permission: 'workflow_view',
        menuActive: [
          '/program/workflow/list',
          'program/workflow/create',
          'program/workflow/edit',
          'program/workflow/view',
          '/program/workflow/flow-list',
        ],
      },
      {
        icon: 'dynamic_form',
        name: 'rule_builder',
        path: '/program/rules-builder/list',
        permission: 'rule_builder_view',
        menuActive: [
          '/program/rules-builder/list',
          '/program/rules-builder/create',
          '/program/rules-builder/edit',
          '/program/rules-builder/view',
        ],
      },
      {
        icon: 'wysiwyg',
        name: 'supporting_text',
        path: '/program/support-text/list',
        permission: 'supporting_text_view',
        menuActive: [
          '/program/support-text/list',
          '/program/support-text/view',
          '/program/support-text/edit',
          '/program/support-text/create',
        ],
      },
    ],
  },
  {
    name: 'configurations',
    icon: 'settings_suggest',
    submenuItem: [
      {
        icon: 'layers',
        name: 'program_configuration',
        path: '/configuration/program-configuration',
        permission: 'program_configuration_view',
        menuActive: ['/configuration/program-configuration'],
      },
      {
        icon: 'design_services',
        name: 'accuracy_configuration',
        path: '/configuration/accuracy-configuration',
        permission: 'accuracy_configuration_view',
        menuActive: ['/configuration/accuracy-configuration', '/configuration/accuracy-configuration/edit'],
      },

      {
        icon: 'card_membership',
        name: 'fee_configurations',
        path: '/configuration/fees-configuration/list',
        permission: 'fee_configuration_view',
        menuActive: [
          '/configuration/fees-configuration/list',
          '/configuration/fees-configuration/create',
          'configuration/fees-configuration/detail-page',
        ],
      },
      {
        icon: 'assignment',
        name: 'assignment_configuration',
        path: '/configuration/assignment-configuration/create',
        permission: 'assignment_configuration_manage',
        menuActive: ['/configuration/assignment-configuration/create'],
      },
      {
        icon: 'timer',
        name: 'timesheet_configurations',
        path: '/configuration/timesheet/list',
        permission: 'timesheet_configuration_view',
        menuActive: ['/configuration/timesheet/list', '/configuration/timesheet/create'],
      },
      {
        icon: 'gavel',
        name: 'timesheet_rule_configurations',
        path: '/configuration/timesheet-rule/list',
        permission: 'timesheet_rule_configuration_view',
        menuActive: ['/configuration/timesheet-rule/list', '/configuration/timesheet-rule/create', '/configuration/timesheet-rule/view'],
      },
      {
        icon: 'account_balance_wallet',
        name: 'expense_configurations',
        path: '/configuration/expense-configuration/list',
        permission: 'expense_configuration_view',
        menuActive: ['/configuration/expense-configuration/list', '/configuration/expense-configuration/create'],
      },
      {
        icon: 'receipt_long',
        name: 'invoice_configuration',
        path: '/configuration/invoice-configuration/create',
        permission: 'invoice_configuration_manage',
        menuActive: ['/configuration/invoice-configuration/create'],
      },
      {
        icon: 'layers',
        name: 'credentialing',
        path: '/configuration/credentialing',
        permission: 'view_credentialing',
        menuActive: ['/configuration/credentialing'],
      },
    ],
  },
  {
    name: 'user',
    icon: 'group',
    submenuItem: [
      {
        name: 'organization_users',
        icon: 'supervised_user_circle',
        path: '/users/organization-users/list',
        permission: 'user_view',
        menuActive: ['/users/organization-users/list', '/users/organization-users/profile-view'],
      },
      {
        icon: 'people_alt',
        name: 'program_users',
        path: '/users/list',
        permission: 'user_view',
        menuActive: ['/users/list', '/users/profile-view'],
      },
      // {
      //   icon: 'manage_accounts',
      //   name: 'User roles',
      // },

      {
        name: 'user_roles',
        icon: 'manage_accounts',
        path: '/users/roles',
        permission: 'user_role_view',
        menuActive: ['/users/roles'],
      },
      {
        name: 'password_policies',
        icon: 'manage_accounts',
        path: '/users/password-policy',
        permission: 'password_policies_view',
        menuActive: ['/users/password-policy']
      }
    ],
  },
  {
    name: 'rate',
    icon: 'credit_card',
    submenuItem: [
      {
        icon: 'functions',
        name: 'rate_type',
        path: '/rate/rate-factor/list',
        permission: 'rate_factor_view',
        menuActive: ['/rate/rate-factor/list'],
      },
      {
        icon: 'payments',
        name: 'rate_cards',
        path: '/rate/rate-card/list',
        permission: 'rate_card_view',
        menuActive: ['/rate/rate-card/list', '/rate/rate-card/details'],
      },
      {
        icon: 'request_quote',
        name: 'Cost Component',
        path: '/rate/cost-component/list',
        permission: 'cost_component_view',
        menuActive: ['/rate/cost-component/list', '/rate/cost-component/create'],
      },
      {
        icon: 'calculate',
        name: 'Cost Component Group',
        path: '/rate/cost-component-group/list',
        permission: 'cost_component_view',
        menuActive: ['/rate/cost-component-group/list', '/rate/cost-component-group/create'],
      },
    ],
  },
  {
    name: 'job',
    icon: 'work_outline',
    submenuItem: [
      {
        icon: 'local_library',
        name: 'qualifications',
        path: '/job/qualificationsList/list',
        permission: 'qualification_view',
        menuActive: ['/job/qualificationsList/list'],
      },
      {
        icon: 'work_outline',
        name: 'job_templates',
        path: '/job/job-template/list',
        permission: 'job_template_view',
        menuActive: ['/job/job-template/list', '/job/job-template/create', '/job/job-template/view', '/job/job-template/create'],
      },
    ],
  },
  {
    name: 'onboarding',
    icon: 'check_circle',
    submenuItem: [
      {
        icon: 'task_alt',
        name: 'tasks',
        path: '/onboarding/task/list',
        permission: 'task_view',
        menuActive: ['/onboarding/task/list', 'onboarding/task/create', '/mode/view', '/mode/edit'],
      },
      {
        icon: 'playlist_add_check',
        name: 'checklists',
        path: '/onboarding/task/checklist',
        permission: 'checklist_view',
        menuActive: ['/onboarding/task/checklist'],
      },
    ],
  },
  {
    name: 'data_management',
    icon: 'manage_search',
    submenuItem: [
      {
        icon: 'view_stream',
        name: 'custom_field',
        path: '/data-management/custom-field/list',
        permission: 'custom_field_view',
        menuActive: [
          '/data-management/custom-field/list',
          '/data-management/custom-field/create',
          'data-management/custom-field/view',
          '/data-management/custom-field/edit',
        ],
      },
      {
        icon: 'category',
        name: 'reason_codes',
        path: '/data-management/reason-codes',
        permission: 'reason_code_view',
        menuActive: [
          '/data-management/reason-codes',
          '/data-management/reason-codes/reason-code-details',
          '/data-management/reason-codes/edit-reason',
        ],
      },
      {
        icon: 'checklist',
        name: 'picklists',
        path: '/data-management/picklist',
        permission: 'picklist_view',
        menuActive: ['/data-management/picklist'],
      },
      {
        icon: 'workspace_premium',
        name: 'labor_categories',
        path: '/data-management/labor-categories',
        permission: 'labor_category_view',
        menuActive: ['/data-management/labor-categories', '/data-management/labor-create', '/data-management/labor-view'],
      },
      {
        icon: 'upload_file',
        name: 'upload_utility',
        path: '/data-management/upload-utility',
        permission: 'upload_utility_manage',
        menuActive: ['/data-management/upload-utility'],
      },
      // {
      //   icon: 'tag',
      //   name: 'Account code',
      //   path: '/data-management/setup/account-codes',
      //   permission: null,
      // },
    ],
  },
  {
    name: 'notifications',
    icon: 'notifications',
    submenuItem: [
      {
        name: 'notifications',
        icon: 'notifications',
        path: '/notification/config/list',
        permission: 'notification_view',
        menuActive: ['/notification/config/list', '/notification/config/event/template', '/notification/config/event/template'],
      },
      {
        name: 'notification_preferences',
        icon: 'notification_important',
        path: '/notifications/preferences',
        permission: 'notification_preferences',
        menuActive: ['/notifications/preferences'],
      },
      {
        name: 'notification_log',
        icon: 'all_inbox',
        path: '/notifications/log',
        permission: 'notification_log_view',
        menuActive: ['/notifications/log'],
      },
      {
        name: 'notification_reminder_threshold',
        icon: 'alarm_on',
        path: '/notifications/reminder-threshold',
        permission: 'notification_reminder_threshold_view',
        menuActive: ['/notifications/reminder-threshold'],
      },
      // permission: 'notification_log_view'
    ],
  },
  {
    name: 'vendor_management',
    icon: 'list_alt',
    submenuItem: [
      {
        icon: 'forward_to_inbox',
        name: 'Vendor Invites',
        path: '/vendor/vendor-invites/list',
        permission: 'vendor_invite_view',
        menuActive: ['/vendor/vendor-invites/list','/vendor/vendor-invites/create','/vendor/vendor-invites/view','/vendor/vendor-invites/resend'],
      },
      {
        icon: 'storefront',
        name: 'Vendors',
        path: '/vendor/vendor-list',
        permission: 'vendors_view',
        menuActive: ['/vendor/vendor-list', '/vendor/compliance-list'],
      },
      {
        icon: 'workspaces',
        name: 'vendor_groups',
        path: '/vendor/vendor-group-list',
        permission: 'vendor_group_view',
        menuActive: ['/vendor/vendor-group-list', 'vendor/create-vendor-group', '/vendor/view-vendor-group', '/vendor/edit-vendor-group'],
      },
      {
        icon: 'event_note',
        name: 'vendor_distribution_schedules',
        path: '/vendor/vendor-distribution-list',
        permission: 'vendor_distribution_schedule_view',
        menuActive: ['/vendor/vendor-distribution-list'],
      },
      {
        icon: 'description',
        name: 'vendor_compliance_documents',
        path: '/vendor/vendor-compliance-list',
        permission: 'vendor_compliance_view',
        menuActive: [
          '/vendor/vendor-compliance-list',
          '/vendor/vendor-compliance-create',
          '/vendor/vendor-compliance-view',
          '/vendor/vendor-compliance-create',
        ],
      },
      {
        icon: 'topic',
        name: 'vendor_compliance_document_groups',
        path: '/vendor/vendor-document-group-list',
        permission: 'vendor_compliance_view',
        menuActive: ['/vendor/vendor-document-group-list', '/vendor/vendor-document-group-create', '/vendor/vendor-document-group-view'],
      },
      {
        icon: 'assured_workload',
        name: 'compliance_restriction_rule',
        path: '/vendor/compliance-restriction-rule',
        permission: 'vendor_compliance_restriction_rule_view',
        menuActive: ['/vendor/compliance-restriction-rule'],
      },
      {
        icon: 'handshake',
        name: 'vendor_details',
        path: '/vendor-managment/setup',
        permission: 'vendor_details',
        users: ['VENDOR'],
        menuActive: ['/vendor-managment/setup'],
      },
    ],
  },
];

export default sideBarOptions;
