import { VMSConfig } from '../../../library/smartTable/table/table.model';

export const TableTabsModel = {
    all: { name: 'All Expenses', filter: 'all' },
    submitted: { name: 'Pending Expenses', filter: 'submitted' },
    approved: { name: 'Approved Expenses', filter: 'approved' },
    rejected: { name: 'Rejected Expenses', filter: 'rejected' },
    withdraw: { name: 'Withdrawn Expenses', filter: 'withdraw' },
    draft: { name: 'Draft Expenses', filter: 'draft' },
    track_back: { name: 'Track Back Expenses', filter: 'track_back' },
    in_progress: { name: 'In Progress Expenses', filter: 'in_progress' },
};

export const MiscTableTabsModel = {
    all: { name: 'All Expenses', filter: 'all' },
    submitted: { name: 'Pending Expenses', filter: 'submitted' },
    approved: { name: 'Approved Expenses', filter: 'approved' },
    rejected: { name: 'Rejected Expenses', filter: 'rejected' },
    withdraw: { name: 'Withdrawn Expenses', filter: 'withdraw' },
    draft: { name: 'Draft Expenses', filter: 'draft' },
    track_back: { name: 'Track Back Expenses', filter: 'track_back' },
    in_progress: { name: 'In Progress Expenses', filter: 'in_progress' },
};

export const ExpenseWorkerTableModel: VMSConfig = {
    title: 'General Expense List',
    columnList: [
        { name: 'expense_code', title: 'Expense ID',  isSort: true,  isIcon: false, isImage: true, isContact: false, isNumberBadge: false, isNoOption: true, toolTipVisibility : true},
        { name: 'expense_status', title: 'Status',  isSort: true,  isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'worker_id', title: 'Worker ID',  isIcon: false, isImage: false, isContact: false, isNumberBadge: false},
        { name: 'expense_type', title: 'Expense Category', isSort: false, isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'expense_period', title: 'Expense Period', isSort: true, isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'expense_approved_date', title: 'Expense Approved Date', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'vendor_name', title: 'Vendor name',isIcon: true, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'submitted_date', title: 'Submitted Date', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'week_end_date', title: 'Weekending Date', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'items', title: 'Items', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'expense_manager_name', title: 'Expense Manager', isIcon: true, isImage: false, isContact: false, isNumberBadge: false,isManagerList:true, toolTipVisibility : true },
        { name: 'total_billable_amount', title: 'Total Billable Amount', isSort: true, isIcon: false, isImage: false, isContact: false, isNumberBadge: false, isCurrency: true},
        { name: 'assignment_title', title: 'Assignment Name (ID)', isIcon: false, isImage: false, isContact: false, isNumberBadge: false  },
    ],
    isExpand: false,
    isFilter: false,
    showTabs: true,
    tabsList: [
        TableTabsModel.all.name,
        TableTabsModel.submitted.name,
        TableTabsModel.approved.name,
        TableTabsModel.rejected.name,
        TableTabsModel.withdraw.name,
        TableTabsModel.draft.name,
        TableTabsModel.track_back.name,
        TableTabsModel.in_progress.name
    ],
    isSearch: true,
    isSort: false,
    isSetting: true,
    isTopPagination: true,
    isCreate: true,
    isCreateButtonName: 'Add New General Expense',
    density: 'COMFORTABLE',
    permission: 'create_expense'
};

export const ExpenseClientTableModel: VMSConfig = {
    title: 'General Expense List',
    columnList: [
        { name: 'worker_name', title: 'Worker Name',  isIcon: true, isImage: true, isContact: false, isNumberBadge: false, isNoOption: true },
        { name: 'expense_status', title: 'Status', isSort: true, isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'expense_code', title: 'Expense ID', isSort: true, isIcon: false, isImage: false, isContact: false, isNumberBadge: false, toolTipVisibility : true },
        { name: 'worker_id', title: 'Worker ID',  isIcon: false, isImage: false, isContact: false, isNumberBadge: false},
        { name: 'expense_type', title: 'Expense Category', isSort: false, isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'expense_period', title: 'Expense Period', isSort: true, isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'expense_approved_date', title: 'Expense Approved Date', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'vendor_name', title: 'Vendor name',isIcon: true, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'submitted_date', title: 'Submitted Date', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'week_end_date', title: 'Weekending Date', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'hierarchy_title', title: 'Hierarchy', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        // { name: 'hierarchy_title', title: 'Hierarchy', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'items', title: 'Items', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'expense_manager_name', title: 'Expense Manager',isIcon: true, isImage: false, isContact: false, isNumberBadge: false,isManagerList:true, toolTipVisibility : true },
        { name: 'total_billable_amount', title: 'Total Expense Amount', isSort: true, isIcon: false, isImage: false, isContact: false, isNumberBadge: false, isCurrency: true },
        { name: 'assignment_title', title: 'Assignment Name (ID)', isIcon: false, isImage: false, isContact: false, isNumberBadge: false, isOpenView: true, permission: 'view_assignment' }
    ],
    isExpand: false,
    isFilter: false,
    showTabs: true,
    tabsList: [
        TableTabsModel.all.name,
        TableTabsModel.submitted.name,
        TableTabsModel.approved.name,
        TableTabsModel.rejected.name,
        TableTabsModel.withdraw.name,
        TableTabsModel.track_back.name,
        TableTabsModel.in_progress.name
    ],
    isSearch: true,
    isSort: false,
    isSetting: true,
    isTopPagination: true,
    isCreate: true,
    isCreateButtonName: 'Add New General Expense',
    density: 'COMFORTABLE',
    isSelectSubmitButton: false,
    isSelectSubmitButtonName: 'Mass Approve',
    isCheckboxOption: false,
    tableWidth: "100%",
    permission: 'create_expense',
    downloadOptions: { csvOption: false, excelOption: false, pdfOption: false}, //new flag
    isPendingReportButton: false,
};

export const ExpenseVendorTableModel: VMSConfig = {
    title: 'General Expense List',
    columnList: [
        { name: 'expense_code', title: 'Expense ID', isSort: true, isIcon: false, isImage: true, isContact: false, isNumberBadge: false, isNoOption: true, toolTipVisibility : true },
        { name: 'expense_status', title: 'Status', isSort: true, isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'worker_name', title: 'Worker Name',  isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'worker_id', title: 'Worker ID',  isIcon: false, isImage: false, isContact: false, isNumberBadge: false},
        { name: 'expense_type', title: 'Expense Category', isSort: false, isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'expense_period', title: 'Expense Period', isSort: true, isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'expense_approved_date', title: 'Expense Approved Date', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'vendor_name', title: 'Vendor name',isIcon: true, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'expense_manager_name', title: 'Expense Manager', isIcon: false, isImage: false, isContact: false, isNumberBadge: false,isManagerList:true, toolTipVisibility : true },
        { name: 'hierarchy_title', title: 'Hierarchy', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'submitted_date', title: 'Submitted Date', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'week_end_date', title: 'Weekending Date', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'items', title: 'Items', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'total_billable_amount', title: 'Total Expense Amount', isSort: true, isIcon: true, isImage: false, isContact: false, isNumberBadge: false, isCurrency: true },
        { name: 'assignment_title', title: 'Assignment Name (ID)', isIcon: false, isImage: false, isContact: false, isNumberBadge: false, isOpenView: true, permission: 'view_assignment' }
    ],
    isExpand: false,
    isFilter: false,
    showTabs: true,
    tabsList: [
        TableTabsModel.all.name,
        TableTabsModel.submitted.name,
        TableTabsModel.approved.name,
        TableTabsModel.rejected.name,
        TableTabsModel.withdraw.name,
        TableTabsModel.draft.name,
        TableTabsModel.track_back.name,
        TableTabsModel.in_progress.name
    ],
    isSearch: true,
    isSort: true,
    isSetting: true,
    isTopPagination: true,
    isCreate: true,
    isCreateButtonName: 'Add New General Expense',
    density: 'COMFORTABLE',
    permission: 'create_expense',
    isSelectSubmitButton: false,
    isSelectSubmitButtonName: 'Mass Approve',
};

export const ExpenseMspTableModel: VMSConfig = {
    title: 'General Expense List',
    columnList: [
        { name: 'worker_name', title: 'Worker Name', isIcon: true, isImage: true, isContact: false, isNumberBadge: false,
            isNoOption: true },
        { name: 'expense_status', title: 'Status', isSort: true, isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'expense_code', title: 'Expense ID', isSort: true, isIcon: false, isImage: false, isContact: false, isNumberBadge: false, toolTipVisibility : true },
        { name: 'worker_id', title: 'Worker ID',  isIcon: false, isImage: false, isContact: false, isNumberBadge: false},
        { name: 'expense_type', title: 'Expense Category', isSort: false, isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'expense_period', title: 'Expense Period', isSort: true, isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'expense_approved_date', title: 'Expense Approved Date', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'vendor_name', title: 'Vendor name',isIcon: true, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'submitted_date', title: 'Submitted Date', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'week_end_date', title: 'Weekending Date', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'hierarchy_title', title: 'Hierarchy', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'items', title: 'Items', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'expense_manager_name', title: 'Expense Manager', isIcon: true, isImage: false, isContact: false, isNumberBadge: false, isManagerList: true, toolTipVisibility : true },
        { name: 'total_billable_amount', title: 'Total Expense Amount', isSort: true, isIcon: false, isImage: false, isContact: false,
            isNumberBadge: false, isCurrency: true },
        { name: 'assignment_title', title: 'Assignment Name (ID)', isIcon: false, isImage: false, isContact: false,
            isNumberBadge: false, isOpenView: true, permission: 'view_assignment' }
    ],
    isExpand: false,
    isFilter: false,
    showTabs: true,
    tabsList: [
        TableTabsModel.all.name,
        TableTabsModel.submitted.name,
        TableTabsModel.approved.name,
        TableTabsModel.rejected.name,
        TableTabsModel.withdraw.name,
        TableTabsModel.draft.name,
        TableTabsModel.track_back.name,
        TableTabsModel.in_progress.name
    ],
    isSearch: true,
    isSort: false,
    isSetting: true,
    isTopPagination: true,
    isCreate: true,
    isCreateButtonName: 'Add New General Expense',
    density: 'COMFORTABLE',
    isSelectSubmitButton: false,
    isSelectSubmitButtonName: 'Mass Approve',
    isCheckboxOption: false,
    tableWidth: '100%',
    permission: 'create_expense',
    downloadOptions: { csvOption: false, excelOption: false, pdfOption: false}, //new flag
    isPendingReportButton: false,
};

export const ExpenseMiscTableModel: VMSConfig = {
    title: 'Miscellaneous Expense List',
    columnList: [
        { name: 'worker_name', title: 'Worker Name', isIcon: true, isImage: true, isContact: false, isNumberBadge: false, isNoOption: true },
        { name: 'expense_status', isSort: true, title: 'Status', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'worker_id', title: 'Worker ID',  isIcon: false, isImage: false, isContact: false, isNumberBadge: false},
        { name: 'expense_type', title: 'Expense Category', isSort: false, isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'expense_period', title: 'Expense Period', isSort: true, isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'expense_approved_date', title: 'Expense Approved Date', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'vendor_name', title: 'Vendor name',isIcon: true, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'expense_code', isSort: true, title: 'Expense ID', isIcon: false, isImage: false, isContact: false, isNumberBadge: false, toolTipVisibility : true },
        { name: 'submitted_date', title: 'Submitted Date', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'week_end_date', title: 'Weekending Date', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'hierarchy_title', title: 'Hierarchy', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'items', title: 'Items', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'expense_manager_name', title: 'Assignment Manager', isIcon: true, isImage: false, isContact: false, isNumberBadge: false,isManagerList:true, toolTipVisibility : true },
        { name: 'total_billable_amount', title: 'Total Billable Amount', isSort: true, isIcon: false, isImage: false, isContact: false, isNumberBadge: false, isCurrency: true },
        { name: 'assignment_title', title: 'Assignment Name (ID)', isIcon: false, isImage: false, isContact: false, isNumberBadge: false, isOpenView: true, permission: 'view_assignment' }
    ],
    isExpand: false,
    isFilter: false,
    showTabs: true,
    tabsList: [
        MiscTableTabsModel.all.name,
        MiscTableTabsModel.submitted.name,
        MiscTableTabsModel.approved.name,
        MiscTableTabsModel.rejected.name,
        MiscTableTabsModel.withdraw.name,
        MiscTableTabsModel.draft.name,
        MiscTableTabsModel.track_back.name,
        TableTabsModel.in_progress.name
    ],
    isSearch: true,
    isSort: true,
    isSetting: true,
    isTopPagination: true,
    isCreate: true,
    isCreateButtonName: 'Add New Miscellaneous Expense',
    density: 'COMFORTABLE',
    permission: 'create_misc_expense'
};

export const ExpenseMiscClientTableModel: VMSConfig = {
    title: 'Miscellaneous Expense List',
    columnList: [
        { name: 'worker_name', title: 'Worker Name', isIcon: true, isImage: true, isContact: false, isNumberBadge: false, isNoOption: true },
        { name: 'expense_status', title: 'Status', isSort: true, isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'worker_id', title: 'Worker ID',  isIcon: false, isImage: false, isContact: false, isNumberBadge: false},
        { name: 'expense_type', title: 'Expense Category', isSort: false, isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'expense_period', title: 'Expense Period', isSort: true, isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'expense_approved_date', title: 'Expense Approved Date', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'vendor_name', title: 'Vendor name',isIcon: true, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'expense_code', title: 'Expense ID', isSort: true, isIcon: false, isImage: false, isContact: false, isNumberBadge: false, toolTipVisibility : true },
        { name: 'submitted_date', title: 'Submitted Date', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'week_end_date', title: 'Weekending Date', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'hierarchy_title', title: 'Hierarchy', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'items', title: 'Items', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'expense_manager_name', title: 'Assignment Manager', isIcon: true, isImage: false, isContact: false, isNumberBadge: false,isManagerList:true, toolTipVisibility : true },
        { name: 'total_billable_amount', title: 'Total Billable Amount', isSort: true, isIcon: false, isImage: false, isContact: false, isNumberBadge: false, isCurrency: true },
        { name: 'assignment_title', title: 'Assignment Name (ID)', isIcon: false, isImage: false, isContact: false, isNumberBadge: false, isOpenView: true, permission: 'view_assignment' }
    ],
    isExpand: false,
    isFilter: false,
    showTabs: true,
    tabsList: [
        MiscTableTabsModel.all.name,
        MiscTableTabsModel.submitted.name,
        MiscTableTabsModel.approved.name,
        MiscTableTabsModel.rejected.name,
        MiscTableTabsModel.withdraw.name,
        MiscTableTabsModel.track_back.name,
        TableTabsModel.in_progress.name
    ],
    isSearch: true,
    isSort: true,
    isSetting: true,
    isTopPagination: true,
    isCreate: true,
    isCreateButtonName: 'Add New Miscellaneous Expense',
    density: 'COMFORTABLE',
    isSelectSubmitButton: false,
    isSelectSubmitButtonName: 'Mass Approve',
    isCheckboxOption: false,
    permission: 'create_misc_expense',
};

export const ExpenseMiscMspTableModel: VMSConfig = {
    title: 'Miscellaneous Expense List',
    columnList: [
        { name: 'worker_name', title: 'Worker Name', isIcon: true, isImage: true, isContact: false, isNumberBadge: false,
            isNoOption: true },
        { name: 'expense_status', title: 'Status', isSort: true, isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'expense_code', title: 'Expense ID', isSort: true, isIcon: false, isImage: false, isContact: false, isNumberBadge: false, toolTipVisibility : true },
        { name: 'worker_id', title: 'Worker ID',  isIcon: false, isImage: false, isContact: false, isNumberBadge: false},
        { name: 'expense_type', title: 'Expense Category', isSort: false, isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'expense_period', title: 'Expense Period', isSort: true, isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'expense_approved_date', title: 'Expense Approved Date', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'vendor_name', title: 'Vendor name',isIcon: true, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'submitted_date', title: 'Submitted Date', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'week_end_date', title: 'Weekending Date', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'hierarchy_title', title: 'Hierarchy', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'items', title: 'Items', isIcon: false, isImage: false, isContact: false, isNumberBadge: false },
        { name: 'expense_manager_name', title: 'Assignment Manager', isIcon: true, isImage: false, isContact: false, isNumberBadge: false,isManagerList:true, toolTipVisibility : true },
        { name: 'total_billable_amount', title: 'Total Billable Amount', isSort: true, isIcon: false, isImage: false, isContact: false,
            isNumberBadge: false, isCurrency: true },
        { name: 'assignment_title', title: 'Assignment Name (ID)', isIcon: false, isImage: false, isContact: false, isNumberBadge: false, isOpenView: true, permission: 'view_assignment' }
    ],
    isExpand: false,
    isFilter: false,
    showTabs: true,
    tabsList: [
        MiscTableTabsModel.all.name,
        MiscTableTabsModel.submitted.name,
        MiscTableTabsModel.approved.name,
        MiscTableTabsModel.rejected.name,
        MiscTableTabsModel.withdraw.name,
        MiscTableTabsModel.draft.name,
        MiscTableTabsModel.track_back.name,
        TableTabsModel.in_progress.name
    ],
    isSearch: true,
    isSort: true,
    isSetting: true,
    isTopPagination: true,
    isCreate: true,
    isCreateButtonName: 'Add New Miscellaneous Expense',
    density: 'COMFORTABLE',
    isSelectSubmitButton: false,
    isSelectSubmitButtonName: 'Mass Approve',
    isCheckboxOption: false,
    permission: 'create_misc_expense',
};
