export enum CustomFieldTypes {
    TextBox = 'TEXT',
    DateTime = 'DATETIME',
    Currency = 'CURRENCY',
    Checkbox = 'CHECKBOX',
    Dropdown = 'DROPDOWN',
    Hyperlink = 'HYPERLINK',
    Date = 'DATE',
    Password = 'PASSWORD',
    Numbers = 'NUMBERS',
    Email = 'EMAIL',
    MultiSelectDropdown = 'MULTI_SELECT_DROPDOWN',
    FileUpload = 'FILE',
    Phone = 'PHONE',
    Radio = 'RADIO',
    Image = 'IMAGE',
    Textarea = 'TEXTAREA',
    ToggleButton = 'TOGGLE',
    Time = 'TIME'
}
